#!/usr/bin/env python3
"""Queue latency issue watcher.

Reads the latest snapshot in ``data/vllm/ci/queue_timeseries.jsonl`` and
opens a GitHub issue when a queue's p90 wait exceeds ``P90_THRESHOLD_MIN``.
Closes the tracked issue when the queue is healthy again (p90 below
``P90_HEALTHY_MIN``) to provide hysteresis — without that margin a queue
flapping around the threshold would churn issue open/close events.

State is stored in ``data/vllm/ci/open_queue_issues.json`` so we remember
which issue number covers which queue across runs. Each authenticated run also
reconciles that state with strictly identified watcher-owned GitHub issues so a
lost state update cannot leave an alert open forever or create a duplicate.

Requires:
  - ``GITHUB_TOKEN`` with ``issues: write`` on the target repo
  - ``GITHUB_REPOSITORY`` ("owner/repo"), set automatically in GH Actions
"""

from __future__ import annotations

import json
import logging
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

import requests

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from vllm.constants import (  # noqa: E402
    AMD_QUEUE_PREFIX,
    QUEUE_ISSUE_MAX_AGE_MIN,
    QUEUE_MIN_WAITING_SAMPLES,
    QUEUE_P90_HEALTHY_MIN,
    QUEUE_P90_TRIGGER_MIN,
)
from vllm.ci.managed_issue import (  # noqa: E402
    IssueLookupError,
    MAX_DIRECT_ISSUE_LOOKUPS,
    bounded_open_issue_candidates,
    fetch_open_issue_candidate,
    repair_issue_labels,
)
from vllm.ci.watcher_state import write_watcher_state  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s", datefmt="%H:%M:%S")
log = logging.getLogger(__name__)

ROOT = Path(__file__).resolve().parent.parent.parent
SNAPSHOTS = ROOT / "data" / "vllm" / "ci" / "queue_timeseries.jsonl"
STATE = ROOT / "data" / "vllm" / "ci" / "open_queue_issues.json"

# Back-compat local aliases — the rest of the module reads these names.
P90_THRESHOLD_MIN = QUEUE_P90_TRIGGER_MIN
P90_HEALTHY_MIN = QUEUE_P90_HEALTHY_MIN
MIN_WAITING_SAMPLES = QUEUE_MIN_WAITING_SAMPLES
LABEL = "queue-latency"
AUTOMATED_LABEL = "automated"
WORKSTREAM_LABEL = "workstream:infra"
OWNERSHIP_MARKER = "<!-- queue-latency-watcher:v1 -->"
OWNED_LABELS = frozenset({LABEL, AUTOMATED_LABEL, WORKSTREAM_LABEL})

GH_API = "https://api.github.com"
DASHBOARD_REPO = "AndreasKaratzas/vllm-ci-dashboard"


def _validate_target_repo(repo: str) -> None:
    if repo.strip().lower() != DASHBOARD_REPO.lower():
        raise RuntimeError(f"Issue automation is restricted to {DASHBOARD_REPO}")


def _gh_headers(token: str) -> dict:
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _issue_label_names(issue: dict) -> set[str]:
    names: set[str] = set()
    for label in issue.get("labels") or []:
        name = label.get("name") if isinstance(label, dict) else label
        if isinstance(name, str) and name:
            names.add(name)
    return names


def _has_exact_ownership_marker(body: str) -> bool:
    return any(line.strip() == OWNERSHIP_MARKER for line in str(body or "").splitlines())


def _queue_from_generated_body(body: str) -> str:
    match = re.search(
        r"^Queue \*\*`([^`\r\n]+)`\*\* exceeded p90 wait of ",
        str(body or ""),
        flags=re.MULTILINE,
    )
    return match.group(1) if match else ""


def _owned_queue_issue(issue: object) -> dict | None:
    """Return a normalized watcher-owned issue, or ``None`` for foreign data.

    Labels alone are intentionally insufficient: a queue name is accepted only
    from the exact body shape generated by this watcher, with its generator
    signature, and the generated title must agree. This lets reconciliation
    repair lost local state without granting a broad label query authority over
    unrelated issues.
    """
    if not isinstance(issue, dict) or "pull_request" in issue:
        return None
    number = issue.get("number")
    if not isinstance(number, int) or isinstance(number, bool) or number <= 0:
        return None
    body = str(issue.get("body") or "")
    has_marker = _has_exact_ownership_marker(body)
    queue = _queue_from_generated_body(body)
    if not queue:
        return None
    if not has_marker:
        # Legacy issues have no cryptographic secret, so adoption requires the
        # complete generated identity rather than a broad label or substring.
        if not OWNED_LABELS.issubset(_issue_label_names(issue)):
            return None
        if not re.search(
            r"^## Queue latency alert$",
            body,
            flags=re.MULTILINE,
        ):
            return None
        if (
            f"This issue will auto-close once p90 drops below {P90_HEALTHY_MIN:.0f}m, "
            not in body
        ):
            return None
        if "*Opened by `queue_issue_watcher.py` from " not in body:
            return None
        title = str(issue.get("title") or "")
        if not re.fullmatch(
            rf"Queue {re.escape(queue)}: p90 wait \d+(?:\.\d+)?m",
            title,
        ):
            return None

    return {
        "number": number,
        "queue": queue,
        "created_at": str(issue.get("created_at") or ""),
        "body": body,
        "labels": issue.get("labels") or [],
        "legacy": not has_marker,
    }


def _list_owned_open_issues(
    token: str,
    repo: str,
    *,
    include_recovery: bool = True,
    tracked_numbers: tuple[int, ...] = (),
) -> list[dict] | None:
    """List a bounded set of issues proven to belong to this watcher.

    ``None`` means the GitHub lookup was incomplete. Callers must distinguish
    that from an authoritative empty list and avoid opening possible duplicates.
    """
    owned_by_number: dict[int, dict] = {}
    tracked = sorted(set(tracked_numbers))
    if len(tracked) > MAX_DIRECT_ISSUE_LOOKUPS:
        log.warning(
            "Queue issue reconciliation has %d tracked numbers; refusing the "
            "bounded direct-lookup limit of %d",
            len(tracked),
            MAX_DIRECT_ISSUE_LOOKUPS,
        )
        return None
    try:
        for number in tracked:
            issue = fetch_open_issue_candidate(
                token,
                repo,
                number,
                request_get=requests.get,
            )
            if issue is None:
                continue
            normalized = _owned_queue_issue(issue)
            if normalized is None:
                raise IssueLookupError(
                    f"tracked queue issue #{number} lost its exact ownership"
                )
            owned_by_number[number] = normalized
        if tracked_numbers and not include_recovery:
            return [owned_by_number[number] for number in sorted(owned_by_number)]
        candidates = bounded_open_issue_candidates(
            token,
            repo,
            durable_label=LABEL,
            recovery_labels=(AUTOMATED_LABEL, WORKSTREAM_LABEL),
            include_recovery=include_recovery,
            exact_candidate=lambda issue: _owned_queue_issue(issue) is not None,
            request_get=requests.get,
        )
    except (IssueLookupError, ValueError) as error:
        log.warning("Queue issue reconciliation lookup failed: %s", error)
        return None
    for issue in candidates:
        normalized = _owned_queue_issue(issue)
        if normalized is not None:
            owned_by_number[normalized["number"]] = normalized
    return [owned_by_number[number] for number in sorted(owned_by_number)]


def _repo_owner(repo: str) -> str:
    return (repo.split("/", 1)[0] if "/" in repo else repo or "AndreasKaratzas").strip() or "AndreasKaratzas"


def _read_last_snapshot() -> dict | None:
    if not SNAPSHOTS.exists():
        return None
    last = None
    with SNAPSHOTS.open() as f:
        for line in f:
            line = line.strip()
            if not line or not line.startswith("{"):
                continue
            try:
                last = json.loads(line)
            except json.JSONDecodeError:
                continue
    return last


def _normalize_open_entry(entry: int | dict, fallback_p90: float = 0.0, fallback_ts: str = "") -> dict:
    """State file historically stored ``{queue: issue_number}`` (a bare int).
    Newer runs persist a dict carrying the issue number plus the peak p90 we've
    seen and the timestamp of our last status comment, so hourly updates don't
    lose context across runs. Accept either shape on read.
    """
    if isinstance(entry, dict):
        entry.setdefault("number", 0)
        entry.setdefault("peak_p90", fallback_p90)
        entry.setdefault("opened_ts", fallback_ts)
        entry.setdefault("last_status_ts", "")
        return entry
    # legacy int
    return {
        "number": int(entry),
        "peak_p90": fallback_p90,
        "opened_ts": fallback_ts,
        "last_status_ts": "",
    }


def _normalize_suppressed_entry(entry: str | dict, fallback_ts: str = "") -> dict:
    if isinstance(entry, dict):
        entry.setdefault("closed_ts", fallback_ts)
        entry.setdefault("last_number", 0)
        return entry
    return {
        "closed_ts": str(entry or fallback_ts or ""),
        "last_number": 0,
    }


def _read_state() -> dict:
    if not STATE.exists():
        return {"open": {}, "suppressed": {}}
    try:
        data = json.loads(STATE.read_text())
        open_raw = data.get("open") or {}
        data["open"] = {q: _normalize_open_entry(v) for q, v in open_raw.items()}
        suppressed_raw = data.get("suppressed") or {}
        data["suppressed"] = {q: _normalize_suppressed_entry(v) for q, v in suppressed_raw.items()}
        return data
    except (json.JSONDecodeError, OSError):
        return {"open": {}, "suppressed": {}}


def _write_state(state: dict) -> None:
    write_watcher_state(STATE, state, state_filename="open_queue_issues.json")


def _format_metric_row(label: str, value: str | int) -> str:
    return f"| {label} | {value} |\n"


def _format_wait(value: float | int | None) -> str:
    return f"{float(value or 0):.1f}m"


def _open_issue_body(queue: str, stats: dict, run_url: str, owner_login: str) -> str:
    return (
        f"{OWNERSHIP_MARKER}\n"
        f"## Queue latency alert\n\n"
        f"Queue **`{queue}`** exceeded p90 wait of {P90_THRESHOLD_MIN:.0f}m in the latest snapshot.\n\n"
        f"| metric | value |\n|---|---|\n"
        f"{_format_metric_row('waiting jobs', int(stats.get('waiting') or 0))}"
        f"{_format_metric_row('running jobs', int(stats.get('running') or 0))}"
        f"{_format_metric_row('p50 wait', _format_wait(stats.get('p50_wait')))}"
        f"{_format_metric_row('p90 wait', _format_wait(stats.get('p90_wait')))}"
        f"{_format_metric_row('p99 wait', _format_wait(stats.get('p99_wait')))}\n"
        f"This issue will auto-close once p90 drops below {P90_HEALTHY_MIN:.0f}m, "
        f"or after 24h if the queue stays elevated.\n\n"
        f"GitHub assignee: {owner_login}.\n\n"
        f"*Opened by `queue_issue_watcher.py` from {run_url}.*\n"
    )


def _open_issue(token: str, repo: str, queue: str, stats: dict, run_url: str) -> int | None:
    title = f"Queue {queue}: p90 wait {stats.get('p90_wait', 0):.1f}m"
    owner_login = _repo_owner(repo)
    body = _open_issue_body(queue, stats, run_url, owner_login)
    try:
        resp = requests.post(
            f"{GH_API}/repos/{repo}/issues",
            headers=_gh_headers(token),
            json={
                "title": title,
                "body": body,
                "labels": [LABEL, AUTOMATED_LABEL, WORKSTREAM_LABEL],
                "assignees": [owner_login],
            },
            timeout=30,
        )
    except requests.RequestException as error:
        log.error("Failed to open issue for %s: %s", queue, error)
        return None
    if resp.status_code >= 300:
        log.error("Failed to open issue for %s: %d %s", queue, resp.status_code, resp.text[:200])
        return None
    try:
        number = (resp.json() or {}).get("number")
    except (AttributeError, ValueError):
        return None
    return number if isinstance(number, int) and not isinstance(number, bool) and number > 0 else None


def _status_update_body(queue: str, stats: dict, peak_p90: float, opened_ts: str, snapshot_ts: str, run_url: str) -> str:
    """Body for the periodic 'still elevated' comment posted while a queue
    remains above trigger. Shows current metrics plus peak-since-open so the
    reader can tell at a glance whether latency is worsening or easing."""
    p90 = float(stats.get("p90_wait") or 0)
    trend = "peaking" if p90 >= peak_p90 - 0.1 else "easing" if p90 < peak_p90 - 5 else "holding"
    return (
        f"### Still elevated ({trend})\n\n"
        f"Snapshot `{snapshot_ts or 'latest'}` \u2014 queue `{queue}` is still above "
        f"the {P90_THRESHOLD_MIN:.0f}m trigger.\n\n"
        f"| metric | value |\n|---|---|\n"
        f"{_format_metric_row('waiting jobs', int(stats.get('waiting') or 0))}"
        f"{_format_metric_row('running jobs', int(stats.get('running') or 0))}"
        f"{_format_metric_row('p50 wait', _format_wait(stats.get('p50_wait')))}"
        f"{_format_metric_row('p90 wait (current)', _format_wait(p90))}"
        f"{_format_metric_row('p90 wait (peak since open)', _format_wait(peak_p90))}"
        f"{_format_metric_row('p99 wait', _format_wait(stats.get('p99_wait')))}\n"
        f"Issue opened at `{opened_ts or 'unknown'}`. Will auto-close once p90 "
        f"drops below {P90_HEALTHY_MIN:.0f}m, or after 24h if the queue stays "
        f"elevated.\n\n"
        f"*Update posted by `queue_issue_watcher.py` from {run_url}.*\n"
    )


def _comment_issue(token: str, repo: str, number: int, body: str) -> bool:
    try:
        resp = requests.post(
            f"{GH_API}/repos/{repo}/issues/{number}/comments",
            headers=_gh_headers(token),
            json={"body": body},
            timeout=30,
        )
    except requests.RequestException as error:
        log.warning("Comment on #%d failed: %s", number, error)
        return False
    if resp.status_code >= 300:
        log.warning("Comment on #%d failed: %d", number, resp.status_code)
        return False
    return True


def _ensure_owner_assigned(token: str, repo: str, number: int) -> bool:
    owner_login = _repo_owner(repo)
    try:
        resp = requests.post(
            f"{GH_API}/repos/{repo}/issues/{number}/assignees",
            headers=_gh_headers(token),
            json={"assignees": [owner_login]},
            timeout=30,
        )
    except requests.RequestException as error:
        log.warning("Assign owner on #%d failed: %s", number, error)
        return False
    if resp.status_code not in {200, 201}:
        log.warning("Assign owner on #%d failed: %d", number, resp.status_code)
        return False
    return True


def _close_issue(token: str, repo: str, number: int) -> bool:
    try:
        resp = requests.patch(
            f"{GH_API}/repos/{repo}/issues/{number}",
            headers=_gh_headers(token),
            json={"state": "closed", "state_reason": "completed"},
            timeout=30,
        )
    except requests.RequestException as error:
        log.warning("Close #%d failed: %s", number, error)
        return False
    if resp.status_code >= 300:
        log.warning("Close #%d failed: %d", number, resp.status_code)
        return False
    return True


def _adopt_legacy_issue(token: str, repo: str, issue: dict) -> bool:
    """Add the exact ownership marker before a legacy issue enters state."""
    body = str(issue.get("body") or "")
    if _has_exact_ownership_marker(body):
        return True
    try:
        resp = requests.patch(
            f"{GH_API}/repos/{repo}/issues/{issue['number']}",
            headers=_gh_headers(token),
            json={"body": f"{OWNERSHIP_MARKER}\n{body}"},
            timeout=30,
        )
    except requests.RequestException as error:
        log.warning("Adopt legacy queue issue #%d failed: %s", issue["number"], error)
        return False
    if resp.status_code >= 300:
        log.warning("Adopt legacy queue issue #%d failed: %d", issue["number"], resp.status_code)
        return False
    return True


def _parse_ts(ts: str) -> datetime | None:
    if not ts:
        return None
    try:
        return datetime.fromisoformat(ts.replace("Z", "+00:00")).astimezone(timezone.utc)
    except ValueError:
        return None


def _issue_age_minutes(opened_ts: str, snapshot_ts: str) -> float:
    opened = _parse_ts(opened_ts)
    snap = _parse_ts(snapshot_ts)
    if not opened or not snap:
        return 0.0
    return max(0.0, (snap - opened).total_seconds() / 60.0)


def _reconcile_owned_open_issues(
    token: str,
    repo: str,
    open_map: dict[str, dict],
    suppressed_map: dict[str, dict],
    queues: dict,
    snapshot_ts: str,
    run_url: str,
) -> bool:
    """Recover watcher-owned issues that disappeared from local state.

    The oldest owned issue for a queue is canonical unless state already tracks
    another open owned issue. Extra owned issues are closed as duplicates. A
    suppressed queue keeps no open issue. ``False`` means discovery failed and
    callers must not open a new issue whose prior state may merely be missing.
    """
    recovery_needed = not open_map or any(
        queue.startswith(AMD_QUEUE_PREFIX)
        and queue not in open_map
        and float((stats or {}).get("p90_wait") or 0) >= P90_THRESHOLD_MIN
        and int((stats or {}).get("waiting") or 0) >= MIN_WAITING_SAMPLES
        for queue, stats in queues.items()
    )
    discovered = _list_owned_open_issues(
        token,
        repo,
        include_recovery=recovery_needed,
        tracked_numbers=tuple(
            int(entry.get("number") or 0)
            for entry in open_map.values()
            if int(entry.get("number") or 0) > 0
        ),
    )
    if discovered is None:
        return False

    by_queue: dict[str, list[dict]] = {}
    for issue in discovered:
        by_queue.setdefault(issue["queue"], []).append(issue)

    # A complete open-issue scan is authoritative. Never keep mutating a local
    # number that no longer resolves to a provably owned open issue. Treat a
    # still-unhealthy queue like a manual close: suppress it until recovery so
    # a removed marker cannot cause either a foreign mutation or a duplicate.
    for queue in sorted(set(open_map) - set(by_queue)):
        entry = open_map.pop(queue)
        stats = queues.get(queue) or {}
        p90 = float(stats.get("p90_wait") or 0)
        if queue.startswith(AMD_QUEUE_PREFIX) and p90 > P90_HEALTHY_MIN:
            suppressed_map[queue] = {
                "closed_ts": snapshot_ts,
                "last_number": int(entry.get("number") or 0),
            }
            log.warning(
                "Tracked queue issue #%d for %s is no longer an exactly owned "
                "open issue; suppressing until the queue recovers",
                int(entry.get("number") or 0),
                queue,
            )
        else:
            suppressed_map.pop(queue, None)
            log.info(
                "Dropped closed or unowned tracked queue issue #%d for healthy %s",
                int(entry.get("number") or 0),
                queue,
            )

    for queue, issues in sorted(by_queue.items()):
        issues.sort(key=lambda issue: issue["number"])
        tracked = open_map.get(queue) or {}
        tracked_number = int(tracked.get("number") or 0)
        keeper = None
        if queue not in suppressed_map:
            keeper = next(
                (issue for issue in issues if issue["number"] == tracked_number),
                issues[0],
            )
            if not repair_issue_labels(
                token,
                repo,
                keeper,
                OWNED_LABELS,
                request_post=requests.post,
            ):
                log.warning(
                    "Could not repair durable labels on queue issue #%d",
                    keeper["number"],
                )
                return False
            if keeper.get("legacy") and not _adopt_legacy_issue(
                token, repo, keeper
            ):
                return False
            stats = queues.get(queue) or {}
            current_p90 = float(stats.get("p90_wait") or 0)
            if tracked_number != keeper["number"]:
                open_map[queue] = {
                    "number": keeper["number"],
                    "peak_p90": current_p90,
                    "opened_ts": keeper["created_at"],
                    "last_status_ts": "",
                }
                log.info(
                    "Recovered watcher-owned issue #%d for %s from GitHub",
                    keeper["number"],
                    queue,
                )
            elif not _parse_ts(str(tracked.get("opened_ts") or "")):
                tracked["opened_ts"] = keeper["created_at"]
        else:
            # Suppression means the lifecycle has already bounded this alert;
            # any still-open owned issue is an orphan from a failed state push.
            open_map.pop(queue, None)

        for issue in issues:
            if keeper is not None and issue["number"] == keeper["number"]:
                continue
            number = issue["number"]
            if issue.get("legacy") and not _adopt_legacy_issue(
                token, repo, issue
            ):
                return False
            if keeper is None:
                reason = (
                    "Closing this watcher-owned queue-latency issue during state "
                    "reconciliation because the queue is already suppressed."
                )
            else:
                reason = (
                    "Closing this duplicate watcher-owned queue-latency issue during "
                    f"state reconciliation. #{keeper['number']} remains canonical."
                )
            if not _comment_issue(
                token, repo, number, f"{reason}\n\n*{run_url}*"
            ):
                return False
            if not _close_issue(token, repo, number):
                return False
            log.info("Closed reconciled queue-latency issue #%d for %s", number, queue)

    return True


def run() -> int:
    token = os.getenv("GITHUB_TOKEN")
    repo = os.getenv("GITHUB_REPOSITORY") or DASHBOARD_REPO
    _validate_target_repo(repo)
    run_id = os.getenv("GITHUB_RUN_ID", "")
    run_url = f"https://github.com/{repo}/actions/runs/{run_id}" if run_id else f"https://github.com/{repo}"

    snapshot = _read_last_snapshot()
    if not snapshot:
        log.warning("No snapshot to evaluate; exiting")
        return 0

    state = _read_state()
    open_map: dict[str, dict] = dict(state.get("open", {}))
    suppressed_map: dict[str, dict] = dict(state.get("suppressed", {}))
    queues = snapshot.get("queues", {}) or {}
    snapshot_ts = snapshot.get("ts", "")

    # Only AMD queues are in scope — NVIDIA/CPU/partner queues are noisy
    # and out of this dashboard's responsibility.
    hot = []
    for q, s in queues.items():
        if not q.startswith(AMD_QUEUE_PREFIX):
            continue
        p90 = float(s.get("p90_wait") or 0)
        waiting = int(s.get("waiting") or 0)
        if p90 >= P90_THRESHOLD_MIN and waiting >= MIN_WAITING_SAMPLES:
            hot.append((q, s, p90))

    if not token:
        log.warning("GITHUB_TOKEN not set; skipping GitHub mutations")
        _write_state(state)
        return 0

    if not _reconcile_owned_open_issues(
        token,
        repo,
        open_map,
        suppressed_map,
        queues,
        snapshot_ts,
        run_url,
    ):
        log.error(
            "Queue issue reconciliation was incomplete; refusing every issue "
            "mutation and preserving the prior ledger"
        )
        return 0

    healthy = []
    expired = []
    for q, entry in open_map.items():
        # Auto-close any stale non-AMD issues that predate the AMD-only filter.
        s = queues.get(q) or {}
        p90 = float(s.get("p90_wait") or 0)
        if not q.startswith(AMD_QUEUE_PREFIX) or p90 <= P90_HEALTHY_MIN:
            healthy.append((q, entry["number"], p90, s))
            continue
        age_min = _issue_age_minutes(entry.get("opened_ts") or "", snapshot_ts)
        if age_min >= QUEUE_ISSUE_MAX_AGE_MIN:
            expired.append((q, entry["number"], age_min))

    log.info(
        "Evaluated %d queues: %d hot, %d healthy and %d expired with open issues",
        len(queues),
        len(hot),
        len(healthy),
        len(expired),
    )

    for q, number, age_min in expired:
        if not _ensure_owner_assigned(token, repo, number):
            continue
        if not _comment_issue(
            token,
            repo,
            number,
            "Closing this queue-latency issue after 24h to keep the operational "
            "backlog bounded. The queue is still elevated, but no new queue-latency "
            "issue will open until it first returns to healthy.\n\n"
            f"*{run_url}*",
        ):
            continue
        if not _close_issue(token, repo, number):
            continue
        suppressed_map[q] = {
            "closed_ts": snapshot_ts,
            "last_number": number,
        }
        open_map.pop(q, None)
        log.info("Closed stale queue-latency issue #%d for %s after %.1fm", number, q, age_min)

    for q, number, p90, s in healthy:
        if not _ensure_owner_assigned(token, repo, number):
            continue
        if not _comment_issue(
            token,
            repo,
            number,
            f"Queue healthy again: p90={p90:.1f}m (threshold {P90_HEALTHY_MIN:.0f}m). Closing.\n\n*{run_url}*",
        ):
            continue
        if not _close_issue(token, repo, number):
            continue
        open_map.pop(q, None)
        log.info("Closed issue #%d for %s", number, q)

    for q, s, p90 in hot:
        if q in suppressed_map:
            log.info("Suppressed queue alert for %s while it remains unhealthy", q)
            continue
        if q in open_map:
            # Already tracked — post an hourly status update so the issue
            # reflects current latency instead of freezing at the metrics
            # captured when the issue was first opened. Track peak p90 so the
            # comment can call out whether latency is worsening or easing.
            entry = open_map[q]
            number = entry["number"]
            if not _ensure_owner_assigned(token, repo, number):
                continue
            peak = max(float(entry.get("peak_p90") or 0), p90)
            opened_ts = entry.get("opened_ts") or ""
            body = _status_update_body(q, s, peak, opened_ts, snapshot_ts, run_url)
            if not _comment_issue(token, repo, number, body):
                continue
            entry["peak_p90"] = peak
            entry["last_status_ts"] = snapshot_ts
            log.info("Posted status update to #%d (%s p90=%.1f peak=%.1f)", number, q, p90, peak)
            continue
        number = _open_issue(token, repo, q, s, run_url)
        if number is not None:
            open_map[q] = {
                "number": number,
                "peak_p90": p90,
                "opened_ts": snapshot_ts,
                "last_status_ts": "",
            }
            log.info("Opened issue #%d for %s", number, q)

    for q in list(suppressed_map.keys()):
        s = queues.get(q) or {}
        p90 = float(s.get("p90_wait") or 0)
        if not q.startswith(AMD_QUEUE_PREFIX) or p90 <= P90_HEALTHY_MIN:
            suppressed_map.pop(q, None)
            log.info("Cleared suppression for %s after the queue returned healthy", q)

    state["open"] = open_map
    state["suppressed"] = suppressed_map
    state["last_run"] = snapshot_ts
    _write_state(state)
    return 0


if __name__ == "__main__":
    sys.exit(run())
