"""Smoke test for the dashboard bundle (docs/).

A real headless-browser test would require Node or Playwright, neither of
which is available in this repo's venv. Instead we verify the contract
statically:

1. ``docs/index.html`` references every JS module we ship
2. Each referenced JS file exists and has balanced braces/parens
3. Every ``fetch('data/...')`` call in the JS points at a file that
   exists under ``data/`` (or is one we know may not have been
   generated yet — whitelisted)
4. No JS file references the old per-file ``h()`` helper signature
   conflicting with the shared ``el()`` factory (regression guard for
   the Phase 1 de-duplication)
"""

from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent.parent
DOCS = ROOT / "docs"
JS = DOCS / "assets" / "js"
DATA = ROOT / "data"

# Files that the collectors may not have written yet on a fresh clone.
OPTIONAL_DATA_FILES = {
    "data/vllm/ci/hotness.json",
    "data/vllm/ci/group_changes.json",
    # Written by the GitHub Home collector when its Project V2 query succeeds.
    # It can be absent on a fresh clone before the first collection.
    "data/vllm/ci/project_items.json",
    # Split from operations_v2.json during collection/site assembly. The
    # bundle directory is intentionally gitignored and absent on a fresh clone.
    "data/vllm/ci/operations_v2/ownership.json",
    "data/vllm/ci/operations_v2/reliability.json",
    # Generated by the independent lifecycle collector and copied into Pages
    # only after its first successful run. The live raw asset remains primary.
    "data/vllm/ci/queue_lifecycle.json",
    # Derived from private publication_state.json by scripts/build_site.py.
    "data/vllm/ci/publication_status.json",
}


# Matches ``<!-- ... -->`` including across newlines. CSP documentation in the
# <head> block embeds example strings like ``<script src="evil.com/…">`` to
# explain what CSP blocks; those are comments, not real script references, and
# must not be parsed as such.
_HTML_COMMENT_RE = re.compile(r"<!--.*?-->", re.DOTALL)


def _strip_html_comments(html: str) -> str:
    return _HTML_COMMENT_RE.sub("", html)


def _js_files_referenced_by_index():
    """Return (relative_src, absolute_path) for every local <script src>."""
    html = _strip_html_comments((DOCS / "index.html").read_text())
    refs = re.findall(r'<script[^>]+src="([^"]+)"', html)
    out = []
    for src in refs:
        # Skip remote CDN scripts
        if src.startswith(("http://", "https://", "//")):
            continue
        # Strip cache-busting query string
        clean = src.split("?", 1)[0]
        out.append((clean, DOCS / clean))
    return out


class TestIndexHtml:
    def test_index_exists(self):
        assert (DOCS / "index.html").exists(), "docs/index.html is missing"

    def test_index_references_all_core_js(self):
        html = (DOCS / "index.html").read_text()
        required = [
            "utils.js",
            "publication-status.js",
            "dashboard-nav.js",
            "ops-v2.js",
        ]
        for name in required:
            assert name in html, f"docs/index.html must reference {name}"

    def test_utils_loads_before_dependents(self):
        html = (DOCS / "index.html").read_text()
        utils_pos = html.find("utils.js")
        for dep in ("publication-status.js", "dashboard-nav.js", "ops-v2.js"):
            dep_pos = html.find(dep)
            assert utils_pos < dep_pos, (
                f"utils.js must load before {dep} — it defines the shared h/el helpers"
            )

    def test_retired_control_tools_are_not_loaded(self):
        html = (DOCS / "index.html").read_text()
        for retired in ("auth.js", "token-vault.js", "ci-testbuild.js", "ci-ready.js", "ci-admin.js"):
            assert retired not in html

    def test_queue_lifecycle_renderer_has_a_cache_busted_release(self):
        html = (DOCS / "index.html").read_text()
        assert 'assets/css/ops-v2.css?v=16' in html
        assert 'assets/js/ops-v2.js?v=31' in html
        assert 'assets/js/utils.js?v=62' in html
        assert 'assets/js/dashboard-nav.js?v=4' in html
        source = (JS / "ops-v2.js").read_text()
        assert "assets/js/amd-mirror-inventory.js?v=2" in source
        assert "queueLifecycle: QUEUE_LIFECYCLE_LIVE_BASE + 'queue_lifecycle.json'" in source
        assert "/queue-lifecycle-data/data/vllm/ci/" in source
        assert "queueLifecycleFallback: 'data/vllm/ci/queue_lifecycle.json'" in source


class TestJsFilesPresent:
    def test_every_referenced_js_exists(self):
        missing = [src for src, path in _js_files_referenced_by_index() if not path.exists()]
        assert not missing, f"index.html references JS files that don't exist: {missing}"


class TestJsFileShape:
    """Best-effort structural check without a real JS tokenizer.

    A proper parse requires esprima/Node (not available in this venv).
    What we *can* catch statically: zero-byte files, stray BOM, missing
    IIFE wrapper (every module in this codebase wraps itself in an IIFE
    or a DOMContentLoaded listener).
    """

    @pytest.mark.parametrize("name", [
        "utils.js", "publication-status.js", "dashboard-nav.js", "ops-v2.js",
        "amd-mirror-inventory.js",
    ])
    def test_file_is_nonempty_and_well_formed(self, name):
        path = JS / name
        text = path.read_text()
        assert len(text) > 100, f"{name} is suspiciously small"
        assert not text.startswith("\ufeff"), f"{name} starts with a BOM"
        # Every module is either an IIFE or registers a DOMContentLoaded handler.
        has_iife = re.search(r'\(\s*function\s*\(', text) or re.search(r'\(\s*\(\s*\)\s*=>', text)
        has_domready = "DOMContentLoaded" in text
        has_top_level_const = re.match(r'\s*(const|let|var|function|//)', text) is not None
        assert has_iife or has_domready or has_top_level_const, (
            f"{name} doesn't look like a valid JS module "
            "(no IIFE, no DOMContentLoaded, no top-level declarations)"
        )

    def test_core_js_parses_as_modern_ecmascript(self):
        if not shutil.which("node"):
            pytest.skip("node is not available")
        files = [
            "utils.js", "publication-status.js", "dashboard-nav.js", "ops-v2.js",
            "amd-mirror-inventory.js",
        ]
        script = """
const acorn = require('acorn');
const fs = require('fs');
for (const file of process.argv.slice(1)) {
  acorn.parse(fs.readFileSync(file, 'utf8'), {ecmaVersion: 2022, sourceType: 'script'});
}
"""
        try:
            result = subprocess.run(
                ["node", "-e", script, *[str(JS / file) for file in files]],
                check=False,
                text=True,
                capture_output=True,
            )
        except FileNotFoundError:
            pytest.skip("node is not available")
        if result.returncode and "Cannot find module 'acorn'" in (result.stderr or ""):
            pytest.skip("node acorn parser is not available")
        assert result.returncode == 0, result.stderr

    def test_test_assertion_rate_helper_scales_legacy_values(self):
        if not shutil.which("node"):
            pytest.skip("node is not available")
        script = r"""
const fs = require('fs');
const source = fs.readFileSync(process.argv[1], 'utf8');
const match = source.match(/function testAssertionPassRatePct\(summary, legacyScale\) \{[\s\S]*?\n\}/);
if (!match) throw new Error('testAssertionPassRatePct helper not found');
eval(match[0]);
const cases = [
  [{test_pass_rate_pct: 98.5, pass_rate: 0.1}, 'fraction', 98.5],
  [{pass_rate: 0.875}, 'fraction', 87.5],
  [{pass_rate: 87.5}, 'percent', 87.5],
];
for (const [summary, scale, expected] of cases) {
  const actual = testAssertionPassRatePct(summary, scale);
  if (actual !== expected) {
    throw new Error(`${JSON.stringify(summary)} (${scale}) produced ${actual}, expected ${expected}`);
  }
}
if (testAssertionPassRatePct({}, 'percent') !== null) {
  throw new Error('missing rate should stay unavailable');
}
"""
        result = subprocess.run(
            ["node", "-e", script, str(JS / "utils.js")],
            check=False,
            text=True,
            capture_output=True,
        )
        assert result.returncode == 0, result.stderr



    def test_utils_exposes_parity_family_merge_helper(self):
        text = (JS / "utils.js").read_text()
        assert "function mergeParityGroups" in text, (
            "utils.js should expose a canonical parity-family merge helper for shared dashboard views"
        )
        assert "family_name" in text and "family_key" in text, (
            "mergeParityGroups should understand canonical family metadata from parity_report.json"
        )






    def test_fetchjson_catches_rejected_fetches(self):
        text = (JS / "utils.js").read_text()
        m = re.search(
            r"async function fetchJSON\(url, opts\) \{(.*?)\n\}\n\n// ── Shared element factory",
            text,
            re.DOTALL,
        )
        assert m, "utils.js should define fetchJSON(url)"
        assert "catch" in m.group(1), (
            "fetchJSON should catch network/file-origin failures instead of rejecting and aborting boot"
        )
        assert "AbortController" in m.group(1), (
            "fetchJSON should enforce a timeout so a hanging request cannot stall the whole dashboard forever"
        )


    def test_index_has_boot_fallback_guard(self):
        text = (DOCS / "index.html").read_text()
        assert "__recordBootIssue" in text, (
            "index.html should install a boot-error guard so runtime/script failures are shown on the page"
        )
        assert "__renderBootFallback" in text, (
            "index.html should provide a visible fallback when startup never completes"
        )
        fallback = text[text.index("function activeV2OwnsBoot()") : text.index("window.__bootIssues")]
        assert "document.querySelector('.tab-panel.active')" in fallback
        assert "['loading', 'ready', 'error'].includes(host.dataset.renderState)" in fallback
        assert fallback.index("if (activeV2OwnsBoot()) return;") < fallback.index(
            "last.textContent = 'Dashboard startup failed'"
        ), "the boot watchdog must leave active loading, successful, and handled-error v2 panels to OpsV2"

    def test_public_shell_has_no_browser_auth_hooks(self):
        index = (DOCS / "index.html").read_text()
        nav = (JS / "dashboard-nav.js").read_text()
        assert "__authGate" not in nav
        assert "auth:changed" not in nav
        assert "api.github.com" not in index
        assert "api.buildkite.com" not in index



class TestSiteBuildAssembly:
    def test_shared_build_script_exists(self):
        assert (ROOT / "scripts" / "build_site.py").exists(), (
            "scripts/build_site.py should be the canonical site assembler"
        )

    def test_shared_build_script_preserves_nojekyll(self):
        text = (ROOT / "scripts" / "build_site.py").read_text()
        assert '".nojekyll"' in text, (
            "scripts/build_site.py should emit _site/.nojekyll so GitHub Pages serves "
            "underscored paths like data/vllm/ci/test_results without Jekyll filtering"
        )

    def test_pages_workflows_use_shared_build_script(self):
        for rel in (
            ".github/workflows/deploy-pages.yml",
            ".github/workflows/hourly-master.yml",
            ".github/workflows/pr-preview.yml",
        ):
            text = (ROOT / rel).read_text()
            commands = (
                "python scripts/build_site.py --cache-bust-index",
                '"$CANDIDATE_PYTHON" scripts/build_site.py --cache-bust-index',
                "trusted-base/scripts/build_site.py --cache-bust-index",
            )
            assert any(command in text for command in commands), (
                f"{rel} should assemble the published site via scripts/build_site.py"
            )


@pytest.mark.live_data
class TestDataFetchContract:
    """Every ``fetch('data/...')`` URL must resolve to a committed file.

    Optional-but-expected files are whitelisted so a fresh clone doesn't
    break this test before the collectors have run.
    """

    def _extract_fetch_urls(self):
        pattern = re.compile(r"""['"`](data/[^'"`?\s]+)""")
        urls = set()
        for js in JS.glob("*.js"):
            text = js.read_text()
            for m in pattern.finditer(text):
                url = m.group(1)
                # Skip dynamic URLs with template literal interpolation
                # (e.g. ``data/.../${entryId}/comparison.json``) — the real
                # path is only known at runtime.
                if "${" in url:
                    continue
                urls.add(url)
        return urls

    def test_every_fetch_url_is_a_real_file_or_whitelisted(self):
        for url in self._extract_fetch_urls():
            abspath = ROOT / url
            if abspath.exists():
                continue
            assert url in OPTIONAL_DATA_FILES, (
                f"JS references {url!r} but file doesn't exist and isn't in the optional whitelist. "
                "Either the file needs to be generated, the path is typo'd, or add it to "
                "OPTIONAL_DATA_FILES in this test."
            )


class TestSharedHelperRegression:
    """Phase 1 extracted the per-file ``h()`` factories into shared ``el()``.

    Each module now aliases ``const h = el;`` instead of redefining h().
    This test locks that invariant in so nobody accidentally re-introduces
    a divergent local h().
    """


    def test_utils_exposes_el_factory(self):
        text = (JS / "utils.js").read_text()
        # The factory should be defined at module scope as a function or arrow.
        assert re.search(r'\bfunction\s+el\s*\(', text) or re.search(r'\bel\s*=\s*(function|\()', text), (
            "utils.js must define the shared el() factory"
        )
